### PR TITLE
Only validate unevaluated properties/items on applicable types

### PR DESCRIPTION
**Pull request by EpicWink**
Fixes attribute error when trying to validate `unevaluatedProperties` and `unevaluatedItems` on objects which aren't a `dict` or `list` respectively.

### CODE REVIEW

**Comment by Julian** [comment]
Thanks! The tests for this would actually belong first as a pull request to [the official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/pulls). Could you perhaps give that a shot?

**Comment by EpicWink** [comment]
> The tests for this would actually belong first as a pull request to [the official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/pulls). Could you perhaps give that a shot?

Done, see json-schema-org/JSON-Schema-Test-Suite#550

**Comment by Julian** [comment]
Thanks! I've pulled those in here (and [skipped them on master](https://github.com/python-jsonschema/jsonschema/commit/8223a95933365c1545089719e6148aa25b606464) -- so you should be able to unskip them here in a commit and see these pass.)

Appreciated.

**Comment by EpicWink** [comment]
@Julian that's done. Feel free to review and merge

**Comment by Julian** [comment]
Great! Thanks again

**Pull request merged**
